project:
  type: website
  output-dir: docs

website:
  title: "MEF BDA 503 Fall 2022"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: pjlist.qmd
        text: Progress Journals
      - href: https://berkorbay.github.io/book-of-eda/
        text: Book of EDA

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



