---
title: "BDA 503 Fall 2022"
toc: false
---

# Lecture 7 (Dec 28, 2022)

Presentations!..

# Lecture 6 (Dec 14, 2022)

::: {.callout-tip appearance="simple"} 
**Guest Lecture**: [Onur Karadeli](https://www.linkedin.com/in/onur-karadeli-phd-c-a46a59112/) - Head of Advanced Analytics, RPA, Big Data at SOCAR Turkey
:::

This week's lecture is about introduction to Operations Research and, if time permits, introduction to machine learning. Operations Research is both an historical and an emerging field of AI.

- [OR Primer](https://or-primer.github.io/)
    - [OR with R](https://or-primer.github.io/or-with-r/)
- [Machine Learning Part I](https://mef-bda503.github.io/archive/fall17/files/intro_to_ml.html)  
- [Machine Learning Part II](https://mef-bda503.github.io/archive/fall17/files/intro_to_ml_2.html)


# Lecture 5 (Nov 30, 2022)

::: {.callout-tip appearance="simple"} 
**Guest Lecture**: [İhsancan Özpoyraz](https://www.linkedin.com/in/ihsancan-ozpoyraz/) - Expert Business Consultant at KoçDigital
:::

This week's lecture is more about some intermediate topics about data processing/manipulation. We will mainly learn about joins, long/wide tables. In addition, if time permits, some data parsing from web site sources.

- [dplyr joins](https://stat545.com/join-cheatsheet.html)
    - [Mini live lecture](https://pjournal.github.io/boun-ie48a/files/joins_tutorial_live_lecture.html)
- [Brief tutorial on pivot_longer/pivot_wider](https://pjournal.github.io/boun-ie48a/files/short_tutorial_on_pivot_wider_longer.html)  
- [rvest mini tutorial](https://pjournal.github.io/boun-ie48a/files/rvest_mini_tutorial.html)

# Lecture 4 (Nov 16, 2022)

::: {.callout-tip appearance="simple"} 
**Guest Lecture**: [Burak Balta](https://www.linkedin.com/in/burak-balta/) - Partner & Lead Software Engineer at Sufle
:::

This week's lecture is focused on **Shiny**, an R package to develop interactive dashboards and web pages. Good news! Shiny became recently available for [Python](https://shiny.rstudio.com/py/) (alpha version), so what you learn here is transferrable to Python.

- [Introduction to Shiny (official tutorial)](https://shiny.rstudio.com/tutorial/)
    - [Showcase Gallery](https://shiny.rstudio.com/gallery/)
    - [Cheat Sheet](https://shiny.rstudio.com/articles/cheatsheet.html)
    - [shinyapps.io](https://shinyapps.io)
- Shiny in-class exercise [starter code](https://gist.github.com/berkorbay/5793188b7ebfe013ce64703179f9aa01).

:::{.callout-info appearance="simple"}
**Additional resources**

+ [Mastering Shiny](https://mastering-shiny.org/)  
+ [`golem` R package](https://thinkr-open.github.io/golem/)
+ [Engineering Shiny (advanced)](https://engineering-shiny.org/)
+ [`shinydashboard` R package](https://rstudio.github.io/shinydashboard/) for additional dashboard capabilities.
+ [`shinyMobile` R package](https://rinterface.github.io/shinyMobile/) for mobile app-like capabilities.
:::

:::{.callout-caution appearance="simple"}
**Shiny Assignment - Foreign Students by Nationality (Deadline: ~~Nov 30, 18:30~~ Dec 4, 23:59)**

In this assignment you are asked to prepare a Shiny dashboard using foreign student nationality data of universities taken from Higher Education Council's (YÖK) statistics portal.

+ Download raw data ([link](https://github.com/berkorbay/datasets/raw/master/foreign_students/foreign_students_by_nationality_2021_2022.xlsx)).
+ Preprocess data (converting it to RDS format is recommended) to a workable data frame or tibble. You may work together .
+ Prepare a Shiny app as a single `app.R` file using the data add it to your progress journals under a separate folder with . 
+ Deploy your app to [shinyapps.io](https://shinyapps.io) (use free tier only). (see [documentation link](https://docs.rstudio.com/shinyapps.io/index.html))
+ Add a page to your progress journals with a short introduction of your assignment, a link to shinyapps url, a command to run your app locally. Example code snippet `shiny::runGitHub("BOUN-IE48A/boun-ie48a.github.io",subdir="files/shinyExample/")`
:::

# Lecture 3 (Nov 2, 2022)

::: {.callout-tip appearance="simple"} 
**Guest Lecture**: [Onur Soydan](https://www.linkedin.com/in/onur-soydan-a55aa282/) - Demand Forecasting and Strategic Planning Manager at Uludağ Enerji.
:::

- [Introduction to ggplot2](https://berkorbay.github.io/book-of-eda/ggplot2.html)
- *Supplementary resources*
    - [ggplot2 Cheat Sheet](https://www.maths.usyd.edu.au/u/UG/SM/STAT3022/r/current/Misc/data-visualization-2.1.pdf)


**Group Assignment: Startup Deals (Deadline: 2022-11-16 18:30)**

Your data set is a list of startups getting investments from a variety of domestic and international investors. Data is gathered from [KPMG](https://home.kpmg/tr/tr/home.html) and [212](https://212.vc/)'s [Turkish Startup Investments Review 2021](https://assets.kpmg/content/dam/kpmg/tr/pdf/2022/03/turkish-startup-investments-review-2021.pdf) report. 

Your assignment is to tell the story of Turkish startup investments in 2021 using dplyr, ggplot2 and Quarto/Rmarkdown. Here are the rules and guidelines. 

- Download [Startup Deals 2021 Data](https://github.com/berkorbay/datasets/raw/master/startup_deals/startup_deals_2021.xlsx)
- Get the data in using `readxl::read_excel()` function ([see tutorial](https://readxl.tidyverse.org/)).
- Prepare an Exploratory Data Analysis (EDA) and put that analysis in your "Group Progress Journals (GPJ)"
- Your EDA is graded based on the quality of your findings and the way you present them. 
- Your report should start with "Key Takeaways" (you need to put the exact title) section and it should include 3 to 5 bullets of short sentences about your most striking findings.
- You should include at least one plot using ggplot2.
- Your code should be visible and add the link to the data set (reproducibility). You may make code sections expandable in order to improve readability.
- Add it on your Group Progress Journal. Your report should be reachable from your GPJ.

You are welcome to organize the rest of your report. You are free to determine the theme. For instance, you may focus on e-commerce investments only. You do not need to be comprehensive.

**BONUS**: Prepare a blog post for Medium without code and explain your analysis in two to three paragraphs. 

------------------------------------------------------------------------

# Lecture 2 (Oct 19, 2022)

- [Introduction to dplyr](https://berkorbay.github.io/book-of-eda/dplyr.html)
- *Supplementary resources*
    - [dplyr Cheat Sheet](https://raw.githubusercontent.com/rstudio/cheatsheets/main/data-transformation.pdf)
    - [Book: R for Data Science](https://r4ds.had.co.nz/) by Hadley Wickham & Garrett Grolemund
    - [dplyr with Election Data](https://pjournal.github.io/files/dplyr_elections.html)
- **In-class assignment (Deadline: ~~2022-10-19 21:30~~ 2022-10-21 23:59)** 
    1. Have `nycflights13` R package [ready](https://datatofish.com/install-package-r/). 
    2. Using only the `planes` data set prepare two analyses. Use as many commands of dplyr as possible.
    3. Put analysis and code on your Progress Journal as another page.

------------------------------------------------------------------------

# Lecture 1 (Oct 5, 2022)

- [Introduction to BDA 503](./intro.html)
- [Base R Notes](https://berkorbay.github.io/book-of-eda/base-r.html)
- [Base R in Detail Notes](https://berkorbay.github.io/book-of-eda/base-r-in-detail.html)
- [Quarto - Getting Started](https://quarto.org/docs/get-started/)
- [RMarkdown - Getting Started](https://rmarkdown.rstudio.com/lesson-1.html)
- [Intro to R Presentation (Archive)](https://pjournal.github.io/docs/r_intro/2109/#1)

#### Assignments

-   **RMarkdown/Quarto Assignment (Deadline Oct 19, 18:30):** This is your first assignment.

    1.  Prepare an RMarkdown (.Rmd) or Quarto (.qmd) document. Introduce yourself in one paragraph (Your name surname, your work, your data interests and how you (plan to) use data science skills in your current/future work). Plus, add your Linkedin account link.
    2.  Watch some UseR-2022 videos ([Main Link](https://user2022.r-project.org/program/overview/) - [Recordings Link](https://www.youtube.com/c/useRConference_global/playlists)) and write one of them down on your RMarkdown/Quarto document. Alternatively you can check [RStudio Global 2022](https://www.rstudio.com/conference/2022/2022-conf-talks/) conference talks.
    3.  Find **3 R posts relevant to your interests** and describe them. Get the html output and put it in your progress journal repository.
    4.  Provide a link from your Progress Journal page.

    Check examples from class of 2021: [Emirhan Şahin](https://pjournal.github.io/mef05-liophire/Task1_RMarkDown.nb.html), [Mine Kara](https://pjournal.github.io/mef05-MineKara95/R_Markdown_Homework.html) and [Murat Can Taşar](https://pjournal.github.io/mef05-mctasar/week1.html).

-   **Project Groups (Deadline Nov 1, 17:30)**:

    1.  Form your project groups of either 4 or 5 people *(not fewer, not more)*. You may write to your instructor via Slack or email to find you a group or find a student for your group.
    2.  Pick one of the group names below and email the instructor with your group name and members *(first come first served)*. Remember, once set, you cannot change your group name or members.
        1.  Western Shore
        2.  Peace and Trust
        3.  Silver Linings
        4.  Whole Lotta Love
        5.  Time and Space
        6.  Ramble On
        7.  Summer Moon
        8.  Yellow Desert
        9.  Honey Drip
        10. Rain Song

    *Unassigned students and names will be randomly assigned by the instructor after the deadline.*

------------------------------------------------------------------------

# Week 0

This course benefits from DataCamp for the Classroom program. See details [here](https://www.datacamp.com/groups/education?ref=mefbda503).

Some light reading (blog posts)

-   [About recent developments with RStudio (Posit) and R's future (2022)](https://medium.com/berk-orbay/convergence-of-data-science-languages-ff2214665f3)
-   [Student projects of previous years (2020)](https://medium.com/berk-orbay/student-data-analysis-projects-with-r-729a8529d5a8)
-   [How this course is structured in previous years (2018)](https://medium.com/@berk.orbay/how-to-teach-an-awesome-data-analysis-course-922f5e5651c0)
-   [Instructor's view on R (2017)](https://medium.com/yes-r-can/why-r-stats-is-the-best-2c09d77de25b)

This semester course webpage went under a significant refurbishment. Course archive is in another repository.

-   [Course Archive](https://mef-bda503.github.io/archive/)
