---
title: "Progress Journals"
---

### Group Progress Journals

See [here](./projects) for group project details.

- [Ramble On](https://pjournal.github.io/mef06g-ramble-on/) (_Theme: Education, Culture, Sport and Tourism_)
- [Peace and Trust](https://pjournal.github.io/mef06g-peace-trust/) (_Theme: Agriculture_)
- [Time and Space](https://pjournal.github.io/mef06g-time-and-space/) (_Theme: Industry_)
- [Honey Drip](https://pjournal.github.io/mef06g-honey-drip/) (_Theme: Construction and Housing_)
- [Summer Moon](https://pjournal.github.io/mef06g-summermoon/) (_Theme: Population and Demography_)

### Student Progress Journals

_Ordered by first name_

- [Arzu Alpan](https://pjournal.github.io/mef06-alpanarzu/)
- [Bengü Üzmez](https://pjournal.github.io/mef06-uzmezb)
- [Berk Özcan](https://pjournal.github.io/mef06-berkozzcan/)
- [Buğra Ayral (missing)](https://pjournal.github.io/)
- [Canseza Avağ Erdurak](https://pjournal.github.io/mef06-avagcanseza/)
- [Doğanbarış Gündoğan](https://pjournal.github.io/mef06-doganbarisgundogan/)
- [Duygu Hatipoğlu (missing)](https://pjournal.github.io/)
- [Ece Acaroğlu](https://pjournal.github.io/mef06-eceacaroglu/)
- [Egemen Onat Atam](https://pjournal.github.io/mef06-EgemenOnatAtam/)
- [Emre Çakmak](https://pjournal.github.io/mef06-cakmakem/)
- [Fazli Mengü Aydin](https://pjournal.github.io/mef06-thisismengu/)
- [Gizem Çinar](https://pjournal.github.io/mef06-ggizemcinar/)
- [Gizem Erdoğan](https://pjournal.github.io/mef06-erdogang90/)
- [Gülhan Demirel Dilek](https://pjournal.github.io/mef06-glhndmrl/)
- [Hacı Bayram Saygili](https://pjournal.github.io/mef06-bbsaygili/)
- [Mehmet Kemal Ucuzcu](https://pjournal.github.io/mef06-mekucz/)
- [Muhammed Ali Gökmen](https://pjournal.github.io/mef06-ali-gokmen/)
- [Nihan Cinisli Köksoy](https://pjournal.github.io/mef06-nihanck/)
- [Orhun Doğan](https://pjournal.github.io/mef06-OrhunDo/)
- [Oytun Güngör](https://pjournal.github.io/mef06-Oytungungor/)
- [Sabri Demirdal](https://pjournal.github.io/mef06-aktas8154/)
- [Tayyip Sinan Ocaktan](https://pjournal.github.io/mef06-ocaktans/)
- [Uğur Özata](https://pjournal.github.io/mef06-ugemir/)
- [Yaser Girit](https://pjournal.github.io/mef06-yasergirit/)
- [Yener Alboğa](https://pjournal.github.io/mef06-yeneralboga/)
- [Yiğit Onay](https://pjournal.github.io/mef06-yigitonay/)
- [Yudum Paçin](https://pjournal.github.io/mef06-yudumpacin/)
- [Zeynep Yağmur Güner](https://pjournal.github.io/mef06-gunerzy/)